var scams_data=  [{
    "id": 1,
    "name": "xn--myetherwallt-leb.com",
    "url": "http://xn--myetherwallt-leb.com",
    "coin": "ETH",
    "category": "Phishing",
    "subcategory": "MyEtherWallet",
    "description": "Google reports site as insecure",
    "reporter": "MyCrypto",
    "ip": "162.255.119.121",
    "nameservers": ["dns2.registrar-servers.com", "dns1.registrar-servers.com"],
    "status": "Inactive"
}, {
    "id": 2,
    "name": "myelherwallel.com",
    "url": "http://myelherwallel.com",
    "coin": "ETH",
    "category": "Phishing",
    "subcategory": "MyEtherWallet",
    "addresses": ["0xd0cc2b24980cbcca47ef755da88b220a82291407"],
    "reporter": "MyCrypto",
    "status": "Offline"
}, {
    "id": 3,
    "name": "myetherwallet.cam",
    "url": "http://myetherwallet.cam",
    "coin": "ETH",
    "category": "Phishing",
    "subcategory": "MyEtherWallet",
    "description": "redirecting to real site but that happened before",
    "reporter": "MyCrypto",
    "status": "Offline"
}, {
    "id": 4,
    "name": "coindash.ru",
    "url": "http://coindash.ru",
    "coin": "ETH",
    "category": "Fake ICO",
    "subcategory": "Coindash",
    "description": "someone plz check",
    "reporter": "MyCrypto",
    "ip": "70.39.97.230",
    "nameservers": ["ns4.afraid.org", "ns2.afraid.org", "ns3.afraid.org", "ns1.afraid.org"],
    "status": "Active"
}, {
    "id": 5,
    "name": "coin-wallet.info",
    "url": "http://coin-wallet.info",
    "coin": "ETH",
    "category": "Phishing",
    "subcategory": "Coindash",
    "description": "scam wallet",
    "reporter": "MyCrypto",
    "status": "Offline"
}, {
    "id": 6,
    "name": "etherswap.org",
    "url": "http://etherswap.org",
    "coin": "ETH",
    "category": "Phishing",
    "subcategory": "Ethereum",
    "addresses": ["0x4cdc1cba0aeb5539f2e0ba158281e67e0e54a9b1"],
    "reporter": "MyCrypto",
    "ip": "162.255.119.17",
    "nameservers": ["dns2.registrar-servers.com", "dns1.registrar-servers.com"],
    "status": "Active"
}, {
    "id": 7,
    "name": "xn--mytherwallet-fvb.com",
    "url": "http://xn--mytherwallet-fvb.com",
    "coin": "ETH",
    "category": "Phishing",
    "subcategory": "MyEtherWallet",
    "description": "The website doesn't seem to be sending the private key anywhere (chrome dev console)\nReport: https://www.digitalocean.com/company/contact/#abuse",
    "reporter": "MyCrypto",
    "status": "Offline"
}, {
    "id": 8,
    "name": "myetherwallet.top",
    "url": "http://myetherwallet.top",
    "coin": "ETH",
    "category": "Phishing",
    "subcategory": "MyEtherWallet",
    "description": "IP has changed, Microsoft reports site as insecure, Poses as MyEtherWallet Tech Support",
    "reporter": "MyCrypto",
    "ip": "199.59.242.151",
    "nameservers": ["ns1.bodis.com", "ns2.bodis.com"],
    "status": "Active"
}, {
    "id": 9,
    "name": "mvetherwallet.com",
    "url": "http://mvetherwallet.com",
    "coin": "ETH",
    "category": "Phishing",
    "subcategory": "MyEtherWallet",
    "description": "Bans people that use whitehat",
    "reporter": "MyCrypto",
    "ip": "23.20.239.12",
    "nameservers": ["ns2.namebrightdns.com", "ns1.namebrightdns.com"],
    "status": "Active"
}, {
    "id": 10,
    "name": "my-etherwallet.com",
    "url": "http://my-etherwallet.com",
    "coin": "ETH",
    "category": "Phishing",
    "subcategory": "Classic Ether Wallet",
    "description": "phishing (linked to *.ether-api.com). did not 404.,MEW Deployed. redirects to classic ether wallet",
    "reporter": "MyCrypto",
    "status": "Offline"
}, {
    "id": 11,
    "name": "myethewallet.net",
    "url": "http://myethewallet.net",
    "coin": "ETH",
    "category": "Phishing",
    "subcategory": "MyEtherWallet",
    "description": "New format; save.php",
    "reporter": "MyCrypto",
    "status": "Offline"
}, {
    "id": 12,
    "name": "my-ether-wallet.com",
    "url": "http://my-ether-wallet.com",
    "coin": "ETH",
    "category": "Phishing",
    "subcategory": "MyEtherWallet",
    "reporter": "MyCrypto",
    "ip": "89.46.108.29",
    "nameservers": ["dns3.arubadns.net", "dns.technorail.com", "dns4.arubadns.cz", "dns2.technorail.com"],
    "status": "Inactive"
}, {
    "id": 13,
    "name": "myetherwallet.com.am",
    "url": "http://myetherwallet.com.am",
    "coin": "ETH",
    "category": "Phishing",
    "subcategory": "MyEtherWallet",
    "reporter": "MyCrypto",
    "status": "Offline"
}, {
    "id": 14,
    "name": "myetherwallet.com.gl",
    "url": "http://myetherwallet.com.gl",
    "coin": "ETH",
    "category": "Phishing",
    "subcategory": "MyEtherWallet",
    "description": "Suspended",
    "reporter": "MyCrypto",
    "status": "Offline"
}, {
    "id": 15,
    "name": "myelherwallet.com",
    "url": "http://myelherwallet.com",
    "coin": "ETH",
    "category": "Phishing",
    "subcategory": "MyEtherWallet",
    "description": "Google already reports site as insecure - Webhost suspended it",
    "reporter": "MyCrypto",
    "nameservers": ["ns1.reg.ru", "ns2.reg.ru"],
    "status": "Offline"
}, {
    "id": 16,
    "name": "my-etherwallet.ch",
    "url": "http://my-etherwallet.ch",
    "coin": "ETH",
    "category": "Phishing",
    "subcategory": "MyEtherWallet",
    "description": "Same as .ac - Can be reported to Cloudflare: https://www.cloudflare.com/abuse/form",
    "reporter": "MyCrypto",
    "status": "Offline"
}, {
    "id": 17,
    "name": "myetherwallet.com.ht",
    "url": "http://myetherwallet.com.ht",
    "coin": "ETH",
    "category": "Phishing",
    "subcategory": "MyEtherWallet",
    "description": "hosting blocked, verified",
    "reporter": "MyCrypto",
    "status": "Offline"
}, {
    "id": 18,
    "name": "MyEtherWallet.ac",
    "url": "http://MyEtherWallet.ac",
    "coin": "ETH",
    "category": "Phishing",
    "subcategory": "MyEtherWallet",
    "description": "MyEtherWallet.ac + my-etherwallet.in + my-ethwallet.com",
    "reporter": "MyCrypto",
    "status": "Offline"
}, {
    "id": 19,
    "name": "my-etherwallet.in",
    "url": "http://my-etherwallet.in",
    "coin": "ETH",
    "category": "Phishing",
    "subcategory": "MyEtherWallet",
    "description": "MyEtherWallet.ac + my-etherwallet.in + my-ethwallet.com",
    "reporter": "MyCrypto",
    "status": "Offline"
}, {
    "id": 20,
    "name": "myetherwallewt.com",
    "url": "http://myetherwallewt.com",
    "coin": "ETH",
    "category": "Phishing",
    "subcategory": "MyEtherWallet",
    "description": "someone plz check",
    "reporter": "MyCrypto",
    "ip": "209.182.216.43",
    "nameservers": ["ns1.dnsowl.com", "ns2.dnsowl.com", "ns3.dnsowl.com"],
    "status": "Offline"
}, {
    "id": 21,
    "name": "coindash.ml",
    "url": "http://coindash.ml",
    "coin": "ETH",
    "category": "Fake ICO",
    "subcategory": "Coindash",
    "description": "someone plz check",
    "reporter": "MyCrypto",
    "ip": "195.20.51.152",
    "status": "Offline"
}, {
    "id": 22,
    "name": "myethwallet.net",
    "url": "http://myethwallet.net",
    "coin": "ETH",
    "category": "Phishing",
    "subcategory": "MyEtherWallet",
    "addresses": ["0x00e01a648ff41346cdeb873182383333d2184dd1", "0x858457daa7e087ad74cdeeceab8419079bc2ca03"],
    "reporter": "MyCrypto",
    "status": "Offline"
}, {
    "id": 23,
    "name": "myetherwaliiet.com",
    "url": "http://myetherwaliiet.com",
    "coin": "ETH",
    "category": "Phishing",
    "subcategory": "MyEtherWallet",
    "description": "parked",
    "reporter": "MyCrypto",
    "status": "Offline"
}, {
    "id": 24,
    "name": "my-ethwallet.com",
    "url": "http://my-ethwallet.com",
    "coin": "ETH",
    "category": "Phishing",
    "subcategory": "MyEtherWallet",
    "description": "MyEtherWallet.ac + my-etherwallet.in + my-ethwallet.com",
    "reporter": "MyCrypto",
    "status": "Offline"
}, {
    "id": 25,
    "name": "myetherwallel.com",
    "url": "http://myetherwallel.com",
    "coin": "ETH",
    "category": "Phishing",
    "subcategory": "MyEtherWallet",
    "description": "Report: https://safebrowsing.google.com/safebrowsing/report_phish/ If have IE / Edge, report there: https://support.microsoft.com/en-us/help/930167/how-to-report-a-phishing-web-site",
    "reporter": "MyCrypto",
    "ip": "77.222.56.185",
    "nameservers": ["ns4.spaceweb.pro", "ns3.spaceweb.pro", "ns1.spaceweb.ru", "ns2.spaceweb.ru"],
    "status": "Offline"
}, {
    "id": 26,
    "name": "ether-wall.com",
    "url": "http://ether-wall.com",
    "coin": "ETH",
    "category": "Phishing",
    "subcategory": "MyEtherWallet",
    "description": "scam wallet",
    "reporter": "MyCrypto",
    "status": "Offline"
}, {
    "id": 27,
    "name": "ether-wall.com",
    "url": "http://ether-wall.com",
    "coin": "ETH",
    "category": "Phishing",
    "subcategory": "MyEtherWallet",
    "description": "scam wallet",
    "reporter": "MyCrypto",
    "status": "Offline"
}, {
    "id": 28,
    "name": "myethervvallet.com",
    "url": "http://myethervvallet.com",
    "coin": "ETH",
    "category": "Phishing",
    "subcategory": "MyEtherWallet",
    "description": "EAL blacklisted",
    "reporter": "MyCrypto",
    "ip": "23.20.239.12",
    "nameservers": ["ns2.namebrightdns.com", "ns1.namebrightdns.com"],
    "status": "Active"
}, {
    "id": 29,
    "category": "Offline",
    "name": "blocklichan.info",
    "url": "http://blocklichan.info",
    "subcategory": "Blockchain.info",
    "reporter": "MyCrypto",
    "status": "Offline"
}, {
    "id": 30,
    "category": "Offline",
    "name": "bloclkicihan.info",
    "url": "http://bloclkicihan.info",
    "subcategory": "Blockchain.info",
    "reporter": "MyCrypto",
    "status": "Offline"
}, {
    "id": 31,
    "name": "district-0x.io",
    "url": "http://district-0x.io",
    "coin": "ETH",
    "category": "Fake ICO",
    "subcategory": "district0x",
    "description": "fake ICO site w/ fake address.",
    "addresses": ["0x240e125c20a4cc84bd6e7f8d1fd07aff4c06d43d"],
    "reporter": "MyCrypto",
    "status": "Offline"
}, {
    "id": 32,
    "name": "myetherwallet.com.ua",
    "url": "http://myetherwallet.com.ua",
    "coin": "ETH",
    "category": "Phishing",
    "subcategory": "MyEtherWallet",
    "description": "EAL blacklisted",
    "reporter": "MyCrypto",
    "status": "Offline"
}, {
    "id": 33,
    "name": "myetherwalliet.com",
    "url": "http://myetherwalliet.com",
    "coin": "ETH",
    "category": "Phishing",
    "subcategory": "MyEtherWallet",
    "description": "(7/17/2017) Up again (7/15/2017) 403    (7/13/2017) did not 404.,MEW Deployed,MEW Weaponised,SSL Invalid - posted to metamask / bittrex",
    "reporter": "MyCrypto",
    "status": "Offline"
}, {
    "id": 34,
    "name": "bitcoin-wallet.net",
    "url": "http://bitcoin-wallet.net",
    "coin": "ETH",
    "category": "Phishing",
    "subcategory": "MyEtherWallet",
    "description": "https://bitcointalk.org/index.php?topic=1689585.20",
    "reporter": "MyCrypto",
    "ip": "18.213.250.117",
    "nameservers": ["ns1.dynadot.com", "ns2.dynadot.com"],
    "status": "Active"
}, {
    "id": 35,
    "name": "ethereum-wallet.net",
    "url": "http://ethereum-wallet.net",
    "coin": "ETH",
    "category": "Phishing",
    "subcategory": "MyEtherWallet",
    "description": "https://bitcointalk.org/index.php?topic=1689585.20",
    "reporter": "MyCrypto",
    "ip": "185.117.155.106",
    "nameservers": ["marjory.ns.cloudflare.com", "kip.ns.cloudflare.com"],
    "status": "Active"
}, {
    "id": 36,
    "name": "www.ethereum-wallet.info",
    "url": "http://www.ethereum-wallet.info",
    "coin": "ETH",
    "category": "Phishing",
    "subcategory": "MyEtherWallet",
    "description": "https://bitcointalk.org/index.php?topic=1689585.20",
    "reporter": "MyCrypto",
    "status": "Offline"
}, {
    "id": 37,
    "name": "Twitter: EthereumWallets",
    "url": "https://twitter.com/EthereumWallets",
    "coin": "ETH",
    "category": "Phishing",
    "subcategory": "MyEtherWallet",
    "description": "https://bitcointalk.org/index.php?topic=1689585.20",
    "reporter": "MyCrypto",
    "ip": "104.244.42.193",
    "nameservers": ["d01-01.ns.twtrdns.net", "d01-02.ns.twtrdns.net", "ns1.p34.dynect.net", "ns2.p34.dynect.net", "ns3.p34.dynect.net", "ns4.p34.dynect.net", "a.r06.twtrdns.net", "b.r06.twtrdns.net", "c.r06.twtrdns.net", "d.r06.twtrdns.net"],
    "status": "Offline"
}, {
    "id": 38,
    "name": "www.ether-wallet.net",
    "url": "http://www.ether-wallet.net",
    "coin": "ETH",
    "category": "Phishing",
    "subcategory": "MyEtherWallet",
    "description": "https://bitcointalk.org/index.php?topic=1689585.20",
    "reporter": "MyCrypto",
    "ip": "209.99.40.223",
    "nameservers": ["dns10.parkpage.foundationapi.com", "dns9.parkpage.foundationapi.com"],
    "status": "Active"
}, {
    "id": 39,
    "name": "myetherwallaet.com",
    "url": "http://myetherwallaet.com",
    "coin": "ETH",
    "category": "Phishing",
    "subcategory": "MyEtherWallet",
    "description": "did not 404.,MEW Deployed. it isn't using the mailArea2() call. It's pulling etherwallet-static from the legit MEW site but pulling master.js from https://s3-us-west-2.amazonaws.com/gigshunt/master.js. JS errors all over the place, not rendering properly. [blacklisted via Levenshtein]",
    "reporter": "MyCrypto",
    "status": "Offline"
}, {
    "id": 41,
    "name": "district0x.net",
    "url": "http://district0x.net",
    "coin": "ETH",
    "category": "Fake ICO",
    "subcategory": "district0x",
    "description": "fake ICO site w/ fake address. Mirrored from district0x.io/ by HTTrack Website Copier/3.x [XR&CO'2014], Fri, 14 Jul 2017 08:59:16 GMT",
    "addresses": ["0x2268751eafc860781074d25f4bd10ded480310b9"],
    "reporter": "MyCrypto",
    "status": "Offline"
}, {
    "id": 42,
    "name": "secure-myetherwallet.com",
    "url": "http://secure-myetherwallet.com",
    "coin": "ETH",
    "category": "Phishing",
    "subcategory": "MyEtherWallet",
    "description": "confirmed phishing, blacklisted. did not 404.,MEW Deployed,MEW Weaponised,SSL Invalid",
    "reporter": "MyCrypto",
    "ip": "184.168.221.52",
    "nameservers": ["ns10.domaincontrol.com", "ns09.domaincontrol.com"],
    "status": "Offline"
}, {
    "id": 43,
    "name": "myetherwallet.biz",
    "url": "http://myetherwallet.biz",
    "coin": "ETH",
    "category": "Phishing",
    "subcategory": "MyEtherWallet",
    "description": "scambot phishers did not 404.,MEW Deployed,MEW Weaponised,SSL VALID! completely server side [blacklisted] <!-- Mirrored from myetherwallet.su/ by HTTrack Website Copier/3.x [XR&CO'2014], Wed, 05 Jul 2017 23:40:20 GMT -->",
    "reporter": "MyCrypto",
    "ip": "103.224.182.249",
    "nameservers": ["ns1.above.com", "ns2.above.com"],
    "status": "Inactive"
}, {
    "id": 44,
    "name": "myetherwallet.cc",
    "url": "http://myetherwallet.cc",
    "coin": "ETH",
    "category": "Phishing",
    "subcategory": "MyEtherWallet",
    "description": "phishing scambot. did not 404.,MEW Deployed,MEW Weaponised,SSL VALID! completely server side [blacklisted]",
    "reporter": "MyCrypto",
    "status": "Offline"
}, {
    "id": 45,
    "name": "myetherwallet.su",
    "url": "http://myetherwallet.su",
    "coin": "ETH",
    "category": "Phishing",
    "subcategory": "MyEtherWallet",
    "description": "phishing. did not 404.,MEW Deployed,MEW Weaponised,SSL Invalid",
    "reporter": "MyCrypto",
    "status": "Offline"
}, {
    "id": 46,
    "name": "myetherwallet.xyz",
    "url": "http://myetherwallet.xyz",
    "coin": "ETH",
    "category": "Phishing",
    "subcategory": "MyEtherWallet",
    "description": "scambot phishers. did not 404.,MEW Deployed,MEW Weaponised,SSL VALID!",
    "reporter": "MyCrypto",
    "status": "Offline"
}, {
    "id": 47,
    "name": "contribute-status.im",
    "url": "http://contribute-status.im",
    "coin": "ETH",
    "category": "Fake ICO",
    "subcategory": "Status",
    "addresses": ["0xadf5b0c2103598fb66a61714152f1d1717d49fe0"],
    "reporter": "MyCrypto",
    "status": "Offline"
}, {
    "id": 48,
    "name": "myethetrwallet.com",
    "url": "http://myethetrwallet.com",
    "coin": "ETH",
    "category": "Phishing",
    "subcategory": "MyEtherWallet",
    "reporter": "MyCrypto",
    "ip": "209.182.216.43",
    "nameservers": ["ns1.dnsowl.com", "ns2.dnsowl.com", "ns3.dnsowl.com"],
    "status": "Offline"
}, {
    "id": 49,
    "name": "myetherwaallet.com",
    "url": "http://myetherwaallet.com",
    "coin": "ETH",
    "category": "Phishing",
    "subcategory": "MyEtherWallet",
    "reporter": "MyCrypto",
    "ip": "209.182.216.43",
    "nameservers": ["ns1.dnsowl.com", "ns2.dnsowl.com", "ns3.dnsowl.com"],
    "status": "Offline"
}, {
    "id": 50,
    "name": "myethsrwallet.com",
    "url": "http://myethsrwallet.com",
    "coin": "ETH",
    "category": "Phishing",
    "subcategory": "MyEtherWallet",
    "reporter": "MyCrypto",
    "ip": "209.182.216.43",
    "nameservers": ["ns3.dnsowl.com", "ns1.dnsowl.com", "ns2.dnsowl.com"],
    "status": "Offline"
}]